### ISSUE TITLE
how to check syntax without evaluating the script?

### ISSUE THREAD

**Issue by roozbehg** [svaarala/duktape-wiki#125]
I could not find any function to let the user check the syntax without evaluating the script. is there any?

**Comment by svaarala** [comment]
You can just `duk_compile()` a script without calling it. For example, if you wanted to compile code in the eval context without calling it, you'd `duk_compile(ctx, DUK_COMPILE_EVAL)`.

**Comment by roozbehg** [comment]
perfect thanks for the quick response.

**Comment by svaarala** [comment]
You're welcome :)
