### ISSUE TITLE
The mistakes in duk_xmove_top example

### ISSUE THREAD

**Issue by akscf** [svaarala/duktape-wiki#219]
Hi.
It seems that you have the mistakes in this example, the arguments order is wrong.

https://duktape.org/api.html#duk_xmove_top
void duk_xmove_top(duk_context *to_ctx, duk_context *from_ctx, duk_idx_t count);

/* Move arguments to the new context.  Note that we need to extend
 * the target stack allocation explicitly.
 */
duk_require_stack(new_ctx, nargs);
duk_xmove_top(ctx, new_ctx, nargs);
^^^^^^^^^^^^^^^^^^^^^
ctx and new_ctx mixed up

......

/* Return the function call result by copying it to the original stack. */
duk_xmove_top(new_ctx, ctx, 1);
^^^^^^^^^^^^^^^^^^^^
and here

**Comment by svaarala** [comment]
Thanks, I'll fix the documentation.
