### ISSUE TITLE
Interpreter not resolving nested assignment as expected.

### ISSUE THREAD

**Issue by benf1977** [svaarala/duktape-wiki#59]
I'm using TypeScript to generate enum code that I'm running in a duktape interpreter:

    var NodeType;
    (function (NodeType) {
        NodeType[NodeType["none"] = 0] = "none";
        NodeType[NodeType["text"] = 1] = "text";
    })(NodeType || (NodeType = {}));

duktape will resolve NodeType["text"] => 1 but not NodeType[1] => "text". I asked about this issue on StackOverflow as well: http://stackoverflow.com/q/33489083/449161

The same code works fine in a browser such as Chrome. Thanks.

**Comment by svaarala** [comment]
I filed an issue in the actual Duktape repo (this repo is for the Wiki): https://github.com/svaarala/duktape/issues/427
